name: Android Build

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      STORE_KSTOREPWD : ${{secrets.STORE_KSTOREPWD}}
      STORE_KEYPWD : ${{secrets.STORE_KEYPWD}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Run Tests
        run: ./gradlew testCustomerProdRelease

      - name: Build Project
        run: ./gradlew assembleCustomerProdRelease