name: Android Build

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      STORE_KSTOREPWD : ${{secrets.STORE_KSTOREPWD}}
      STORE_KEYPWD : ${{secrets.STORE_KEYPWD}}

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK
        uses: action/setup-java@v2
        with:
          java-version: 11

      - name: Run Tests
        run: ./gradlew testCustomerProdRelease

      - name: Build Project
        run: ./gradlew assembleCustomerProdRelease